---
title: "Measurement theory"
categories: ['Measurement theory', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](measurement.html#citation).
:::

This is the landing page for everything related to measurement theory. With measurement theory we mean the [theory](theory.qmd) that explains how the true values of your [construct](your-study/constructs.qmd) lead to the observed scores obtained through your [measurement instrument](measurement/instrument.qmd). 

Below we have specified multiple topics to think about with respect to this.

## Think more about your measurement theory

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Measurement theory
-   [Item](measurement/item.qmd)
-   [Instrument](measurement/instrument.qmd)
-   [Sampling](measurement/sampling.qmd)
-   [Validation](measurement/validation.qmd) 
-   [Measurement Model](measurement/measurement-model.qmd) 

:::

