---
title: "Theory landing page"
categories: ['Your study', 'Theory', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../../resources/styles/apa.csl
citation: true
bibliography: ../../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](theory.html#citation).
:::

This is the landing page for topics related to establishing the <i> theory </i> that ties into your [intensive longitudinal](../../intensive-longitudinal-data.qmd) research.

A theory explains why or how your [process](../../processes.qmd) of interest works the way it does. Theory formation - the building and specification of a theory - is an essential part of ILD research: It helps establish what knowledge we have about about our process, and where we have knowledge gaps. These gaps can then be translated into research questions.

Below we have specified multiple pages where you can read more about theory and theory formation.

## Think more about your theory

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Theory
-   [Theory](../theory.qmd)
-   [Measurement theory](../../measurement/measurement.qmd)
-   [Theory formation]
-   [Phenomena]
-   [From theory to research question]
-   [From research question to theory]
-   [Aligning Theory, Design and Modeling Approach]
:::

