---
title: "Theory"
categories: ['Theory', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: resources/styles/apa.csl
citation: true
bibliography: resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](theory.html#citation).
:::

This is the landing page for everything related to your theory. With (substantive) theory we mean the theory that explains how the [process](processes.qmd) you are studying works. 

Below we have specified multiple topics to think about with respect to how the process you are studying works - such that you can best capture that process with your measurements and analyses.

## Think more about your research question

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Theory
-   [Timescale](theory/timescale.qmd)
-   [Ergodicity](theory/ergodicity.qmd)
-   [Context and Events](theory/context-events.qmd)
-   [Distributions](theory/distribution.qmd) 
<!-- -   [Formal model](\FormalModel_General.qmd) -->
:::

