---
title: "Validation Landing Page"
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name: Ellen Hamaker
    email: e.l.hamaker@uu.nl
    orcid: 
    corresponding: true
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
  - name: Noémi Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: apa.csl
citation: true
bibliography: resources/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](PageTemplate.html#citation).
:::

This is the landing page for everything related to the <i> validation </i> of measurements.

# Validation: A Key Consideration for Measuring ILD

To illustrate the importance of considering the validation of a measurement, consider:

a.  Consideration a

b.  Consideration b

c.  Consideration c

## Think More About Validation

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Validation - Reliability

-   [Reliability for Single Item Measures](reliability_single.qmd)
:::

<!-- ::: {.callout-note collapse="false"} -->

<!-- ## Read more: Time Scales - Capturing Specific Events -->

<!-- -   [Capturing Regime Switches](/TScale_Switches.html) -->

<!-- -   [Event-Relations in ILD Measurement](/EventRelations.html) -->

<!-- -   \[Measurement Burst Designs\] -->

<!-- ::: -->

# Practical Considerations

The following practical considerations are also important for the decision about validation, but are not considered further on this website.

-   Practical consideration 1.

```{=html}
<!--
# Related pages

-   [Measurement coverage, time span, & granularity.](/TScale_MeasCoverage.html)

-   [Measuring and Relating Multiple Constructs Measured at Different Timescales](/TScale_RelatingConstructs.html)

-   [Capturing Regime Switches](/TScale_Switches.html)

-   [Event-Relations in ILD Measurement](/EventRelations.html)

-   [Measurement Burst Designs]
-->
```
