---
title: Regime switching processes
categories: ['Theory', 'Ergodicity', 'Non-stationarity', 'Regime-switching']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-05-26
date-modified: last-modified
author:
  - name:
      given: Sophie W.
      family: Berkhout
    email: s.w.berkhout@uu.nl
    corresponding: true
    orcid: 0000-0002-4890-2754
    affiliations:
      - name: Methods &amp; Statistics Department, Utrecht University
  - name:
      given: Daan
      family: de Jong
    email: d.dejong@uu.nl
    affiliations:
      - name: Methods &amp; Statistics Department, Utrecht University
csl: ../../resources/styles/apa.csl
citation: true
bibliography: ../../resources/bibliographies/regime-switching-processes.bib
google-scholar: true
---

::: callout-caution

## This page is a draft. This page has not been peer-reviewed yet. 

:::

::: {.callout-note}
## Want to cite this page? See [citation info](regime-switching-processes.html#citation).
:::

This page is about what it means when a proces has sudden transitions between multiple regimes, and how to capture these.

Many processes are not stable over time but may have multiple stable states or regimes. For example, an individual can alter between healthy and depressed states over a period of time, or a couple may switch between conflict, neutral, and happy states.

If a process consists of multiple regimes it switches between, it is important to think about how to capture these different regimes and how to capture when the process switches between regimes.

In the following, we discuss how we define a regime and some theoretical considerations for when you want to measure a regime-switching process.

# What is a regime?

There is no clear-cut definition of what a regime is, but a regime is often referred to as a stable state (many ideas about stable states come  from [LINK: Dynamical systems theory]). During a regime, the characteristics of a process do not change over time. Typically, a regime is characterized by certain (statistical) properties, such as a set of parameter values (e.g., a mean and a variance).

A process may have multiple regimes, but it can only be in one regime at a time. We may observe these multiple regimes when we measure a process over time. For example, regimes could have a different mean.

::: {.callout-tip collapse="true"}

## Example: Negative affect and bipolar disorder

Gideon wants to see how negative affect evolves over time in a patient diagnosed with bipolar disorder. The patient switches between depressive and manic states while Gideon tracks their negative affect. By looking at the trajectory of negative affect, Gideon can roughly distinguish periods with a high average of negative affect and low average of negative affect.

:::

# Regime switching

When a process exhibits multiple regimes over time, it has to switch from one regime to the other.
Regime switches are sudden: from one moment to the next, the process of interest is completely taken over by a different regime (but a regime could also be varying continuously over time, see [Time-varying processes]).
A main topic of research is *when* and *how* regime switches take place. 
In the following, we discuss the timing and possible mechanisms of regime switching.

## Timing of regime switches

Regime switching may only be understood if regime switching takes place during the measurement period. Therefore, it is important to think about the timescale of the regime switching process. For example, if regime switching occurs more frequently than the frequency of the measurements, regime switches may be missed.

::: {.callout-tip collapse="true"}

## Example: Social anxiety

Flora tracks daily social anxiety in a single participant. At the end of each day in the study, the participant reports how socially anxious they felt that day on average. Flora finds that the participant's social anxiety is very stable over time. However, the participant feels very distinct states of anxiety or no anxiety during the day depending on whether or not they are in a social situation. As the participant encounters a roughly similar amount of social situations each day, this change in anxiety during the day is not captured in the daily average.
:::

One may also be interested in only capturing a single regime. For example, when we are interested in studying individuals who suffer from depression, we do not want our sample to include participants who recover during the measurement period. Therefore, when interested in a single regime, it is also important to think about when the process of interest is in this regime.

::: {.callout-note collapse="true"}
## Read more: Timescales

-   [Key design aspects related to timescales: Time span, process coverage, and granularity](../timescale/time-span-process-coverage-granularity.qmd)

:::

## Regime switching mechanisms

When a process switches between regimes, we may be interested in the mechanism of this regime switching. We may distinguish three mechanisms that cause a process to switch between regimes: (1) a process may excite itself to switch between regimes; (2) an observed, or manifest, variable causes regime switching in a process; or (3) or an unobserved latent variable causes regime switching in a process. We explain these three mechanisms in more detail below.

### Self-excited regime switching
A process may switch between regimes due to a change in its own properties. These properties are required to vary over time, otherwise a process would always stay in the same regime. To capture a self-excited regime switch in a process, you need to observe the relevant changes in properties.

::: {.callout-tip collapse="true"}

## Example: Binge drinking

Marissa studies individuals that suffer from binge drinking. When the participants start a binge drinking episode, they report the amount of alcoholic beverages consumed in the past hour. When participants consumed at least one alcoholic beverage they were more likely to consume more alcoholic beverages in the near future. However, when they reached a certain total amount of alcoholic beverages during the binge drinking episode, their alcohol consumption decreased.

:::

### Manifest regime switching
There may be an observed variable that controls the regime switches of a process. This manifest variable needs to vary over time as otherwise it cannot control switches in regimes of a process. To capture a regime switch controlled by a change in a manifest variable, one needs to observe this change.

::: {.callout-tip collapse="true"}

## Example: Workload

Akash works for a big company and investigates the effect of workload experienced by his colleagues on burnout symptoms. He measures perceived workload and severeness of several burnout symptoms on a weekly basis. He finds that while a higher workload is associated with worse burnout symptoms the following week, overall burnout symptoms bounce back quickly and tend to fluctuate around a healthy average. However, when a colleague persistently perceives a high workload for at least 6 weeks, the burnout symptoms start fluctuating around a non-healthy average.

:::

### Latent regime switching
Regime switching in a process may also be caused by an unobserved latent construct. To capture a latent regime switching process, one needs to be able to estimate this latent construct in some way. Note that regime switching may also take place based on probabilities (e.g., a process may have a 90% probability to stay in the current regime and a 10% probability to switch to another regime) and this probabilistic process is also seen as latent.

::: {.callout-tip collapse="true"}

## Example: Depression

Ilja studies how the interplay of several depression symptoms cause individuals to switch between depressive and healthy states. He measures the severeness of depression symptoms in participants multiple times per day over several days. On each occasion, he estimates the correlation between the variables and finds overall that when all the correlations are high, an individual is more likely to be in a depressive state at the next moment.

:::

# Not accounting for multiple regimes
It is important to think about whether the process of interest exhibits multiple regimes to be able to capture all relevant aspects of the process. When a process switches between regimes during our measurement period and we do not account for this, we may miss important inferences.
For example, you may assume a process only has one regime with one average, but in reality the process switches between two regimes characterized by different averages. If you only look at the overall average you may come to a different conclusion than when you would have looked at the regime-specific averages.

::: {.callout-tip collapse="true"}

## Example: Happiness

Kayra tracks the happiness of a participant to determine whether this person is happy. The participants reports their happiness every day for a month on a scale from -5 (unhappy) to 5 (happy). After data collection, Kayra computes an average happiness of 2 and concludes that the participant is overall moderately happy. However, after reporting this finding to the participant, they indicated that they felt really unhappy at certain periods. Kayra looks at the trajectory of the reported happiness, and sees that there are periods of low happiness and periods of high happiness. Kayra decides to compute the means for these periods separately, and finds an average of -2 in the unhappy period and an average of 4 in the happy period.
:::

# Practical Considerations

- There may not always be strong theories to determine the amount of regimes in a process. Exploratory analyses may be necessary, where the process needs to be monitored long enough to establish the existance of multiple regimes.
- If you do not know whether there is a control variable that determines when a regime switch takes place and want to measure several different possibilities, bare in mind that longer questionnaires increase the burden on participants and reduce compliance.
- If you want to esimate specific statistical properties within regimes, be aware that some statistical properties may require a larger sample size than others (e.g., a mean needs fewer observations than an autoregression).

# Related pages

- [Stationarity]
- [Time-varying processes]
- [Event-related constructs](../context-events/event-relations.qmd)











