---
title: "Constructs landing page"
categories: ['Your study','Constructs','Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](constructs.html#citation).
:::

This is the landing page for topics related to defining your <i> constructs </i> for your [intensive longitudinal](../intensive-longitudinal-data.qmd) study.

Your constructs are the things you want to measure. In the social sciences, we often cannot directly observe the constructs we are interested in. Instead, we try to indirectly measure them, for example with questionnaires. 

In order to measure our constructs well, we need to build a good understanding of them. This is a key part of both our [substantive theories](../substantive-theory/substantive-theory.qmd) and [measurement theories](../measurement-theory/measurement-theory.qmd). A first step is to conceptually define your construct - you define what you mean exactly with your construct. After that, you can figure out how to operationally define your construct - how to measure it. 

Below we have specified multiple topics that may help conceptually define your construct.

## Think more about your constructs

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Conceptually defining your construct
-   [Conceptually defining your construct]
-   [The ontology of your construct]
-   [Substantive theory](../substantive-theory/substantive-theory.qmd)
-   [Measurement theory](../measurement-theory/measurement-theory.qmd)
:::

