---
title: "Research question landing page"
categories: ['Your study','Research question','Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](research-question.html#citation).
:::

This is the landing page for topics related to defining your <i> research question </i> for your [intensive longitudinal](../intensive-longitudinal-data.qmd) study.

Your research question is the place of departure for making all kinds of decisions with respect to your study design, measurement design, analyses, and via these choices determines the conclusions you will be able to draw. It is hence a good idea to make a research question as clear and precise as possible. Then you will able to evaluate to what extent your choices will allow you to learn what you want to learn, and optimize your design for your question. Specifying your research question may take multiple iterations and refinements. 

Below we have specified multiple topics that may help you do this.

## Think more about your research question

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Generating research questions
-   [Theory formation]
-   [From theory to research question]
-   [Substantive theory]
-   [Measurement theory]
:::

::: {.callout-note collapse="false"}
## Read more: Refining research questions
-   [Different research goals: Description, prediction, causal inference, intervention, explanation]
-   [Conceptually defining your constructs]
-   [Studying inter-individual differences versus intra-individual differences]
:::


<!--  

# Practical Considerations

The following practical considerations are also important for the decision about validation, but are not considered further on this website.

-   Practical consideration 1.-->
