---
title: "Your study landing page"
categories: ['Your study', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](your-study.html#citation).
:::

Your study consists of your research question, theory, conceptual definitions, measurement design, procedural design, analyses, results, and conclusions. A good study, all of these different parts of a study are tailored to each other. 

The MATILDA website aims to help you align your research question with your measurement design in the context of studies that use intensive longitudinal data (ILD) to study social science processes. 

Below we have specified multiple topics to think about with respect to the outset of your study - such as your research question and goals, theory, and research paradigm. 

## Think more about your research question

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: The outset of your study
-   [Research question](research-question.qmd)
-   [Theory](theory.qmd)
-   [Constructs](constructs.qmd)
:::

<!--  

# Practical Considerations

The following practical considerations are also important for the decision about validation, but are not considered further on this website.

-   Practical consideration 1.-->
