---
title: "Time span, process coverage, and granularity"
categories: ['Theory', 'Timescale', 'Granularity', 'Time span', 'Time interval', 'Number of measurements', 'Time frame']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-20
date-modified: last-modified
author:
  - name:
      given: Ellen L.
      family: Hamaker
    email: e.l.hamaker@uu.nl
    orcid: 
    corresponding: true
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../../resources/styles/apa.csl
citation: true
bibliography: ../../resources/bibliographies/time-span-process-coverage-granularity.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
This article builds on @hamaker-23
:::


::: callout-note
## Want to cite this page? See [citation info](time-span-process-coverage-granularity.html#citation).
:::

This page is about about three design aspects in longitudinal research, which determine:  

- the <i> time span </i> of our study, which is the total amount of time between the beginning of our measurements and their ending.

- the <i> coverage</i> of the ongoing process.

- the <i>granularity</i> of our study, which is the temporal resolution with which we observe the process: it can be more or less fine-grained.

The time span, coverage, and granularity that stem from a particular measurement design determine (to a large extent) at which timescales we can study a given process. In the following, we discuss the three critical design aspects, and how these determine the time span, coverage, and granularity of a study.

Note that the designs that are referred to below fall in the categories interval contingent (i.e., measurements are taken at regular intervals, such as a daily diary study) and signal contingent (i.e., measurements are taken when the researcher gives a signal, such as typical in ESM studies). The information here is less relevant for event contingent designs, where the measurements are taking place based on encountering certain situations or experiences (e.g., when a participant has to answer questions each time they had a social interaction or when they smoked a cigarette).


# Key design aspects in longitudinal research

We can distinguish between three key aspects of longitudinal measurement designs (Hamaker, 2023), that is: a) the time frame used in the measurement instrument; b) the time interval between measurements; and c) the number of measurements.


## Time frame of the measurement instrument

When using self-report, oftentimes the participant is asked to answer questions with respect to a specific time frame. Similarly, when obtaining measurements that are not based on self-report, the researcher also has to decide with respect to what time frame to obtain the measures.  
<!-- I initially guessed this would be about the duration of the study. I think this needs a better name to indicate it is not the time frame of the study; ie 'time frame of measurement instrument'. -->

::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is performing an ESM/EMA study, in which participants are asked multiple times a day at (semi-)random time points about their momentary experiences. An example of an item is: "How much tension are you experiencing right now?" Other items are making reference to an episode prior to the beep, such as: "Did something stressful happen since the previous beep?" or "How happy were you during the past hour?" 
:::

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie is performing a daily diary study, in which participants are asked at the end of every day to indicate whether and to what extent they have had certain experiences that day. Examples of the questions are: "Did you go to work today?" and "On average, how energetic did you feel today?". Additionally, there are also a few questions about the most extreme experiences that day, such as: "During the most negative event of the day, how annoyed were you?" 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study

Jennifer performed a panel study, in which she asked participants about their average experiences over a longer period of time. For instance, she asked them: "On average, how confident were you over the past month?". She combines this with measures that are not based on self-report, such as the participants average grade over a semester. 
:::

<!-- Hier expliciet maken hoe dit zich verhoudt tot meettheorie, dwz, waarom is het belangrijk dat men hier over nadenkt bij het opzetten van een design, voorbeelden -->

The time frame needs to be chosen such that we are not averaging over the fluctuations within a person across time that are actually of interest; hence, our time frames should not be too wide in comparison to the timescale at which the dynamics of interest operate. For instance, if we want to study emotion regulation, than having a time frame of two weeks is probably (much) too long. 

Yet, time frames that are too narrow may also be problematic, in that they contain a lot of variation that is rather momentary and may be considered measurement error from the perspective of the actual process we are interested in. For instance, if we are interested in an adolescent's well-being (a concept that is concerned with somewhat more general, longer-lasting experiences rather than momentary experiences), then having ESM measures may contain more momentary information than we are interested in.    

Hence, the [timescale](../timescale.qmd) at which a process is considered to operate, is critical in deciding what time frame of the the measurements is appropriate. 

Furthermore, when using self-report, the time frame also is assumed to play a critical role in the mental processes that underlie the response people give. When the time frame is very short, then it is assumed that people make use of the episodic memory to arrive at an answer. As the time frame increases, it is assumed that individuals at some point switch to their semantic memory [REFERENCE?]. This has also been related to the difference between the experiencing self and the remembering self [REFERENCE?]. 

<!-- Evt andere dingen noemen die iets te maken hebben met time frame en (meet)theorie ; e.g., zijn we geinteresseerd in remembering or experiencing self (read more paginas) Evt IJsbrand inschakelen hiervoor-->



::: {.callout-note collapse="true"}

## Read more: Time frame used in measurement instruments

-   [Retrospective Assessment, Ecological Retrospective Assessment, Ecological Momentary Assessment]

-   [Remembering vs Experiencing Self]

-   [Designing a measurement instrument to target between-person or within-person variance]
:::

## Time interval between measurements

A second key aspect of the longitudinal design is the interval between measurements. These can we long (e.g., a year) or short (e.g., a millisecond), and they may be fixed (i.e., always the same for everyone), or (semi-)random. The latter is often used in self-report studies based on ESM/EMA, as a way to ensure participants are caught while living their daily life, rather than anticipating the next beep. 


::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is performing an ESM/EMA study, in which participants are asked multiple times a day about their momentary experiences. To this end the time between 8am and 9:30pm is divided into blocks of 90 minutes, and within block, at a random time point within that block a beep is given, and the participant is asked to fill out the questionnaire. An additional constraint that can be imposed is that beeps need to be at least 15 minutes apart. The resulting data are thus irregularly spaced in time within the day. Furthermore, these data are characterized by a longer interval for the night break. 
:::


::: {.callout-tip collapse="true"}

## Example: Panel study

Jennifer is interested in the relation between semester reports and motivations of students. She therefore performed a panel study, with intervals between the measurements of 6 months.  
:::

Again, the [timescale](../timescale.qmd) at which the process of interest operates, is important here. If we want to study a process that takes place within a day, we need to obtain multiple measurements within a day, and the time interval between the measurements therefore need to be (much) shorter than a day. If our interest is in a developmental process that takes place over years, than the intervals between the measurements will typically be half a year or a year.


::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is interested in finding out whether there are individual differences in the degree to which positive affect (like: energetic, joyful) peaks in the middle of the day. Hence, she has to obtain enough measurements across the day and across multiple days such that she can reliably estimate individual differences in this pattern. 
:::


::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie uses a daily diary study to see how fulfilled people feel on days that they work compared to days they did not work. She thus needs to make sure that she includes enough of both working and work-free days per person to be able to reliably estimate the (mean) difference.  
:::

<!-- Hier expliciet maken waarom dit belangrijk is om over na te denken mbt meet(theory) en substantive theory/beantwoorden onderzoeksvraag. -->
<!-- Evt andere dingen noemen die iets te maken hebben met theorie ; e.g., wat gebeurt er in between metingen/intervals. Evt hier expliciet link maken naar 'wat als verschillende variabelen gemeten zijn met verschillende intervals, verwijzen naar sophie pagina. -->


::: {.callout-note collapse="true"}

## Read more: Time Intervals between Measurements

-   [Constructs Measured at Different Timescales](/RelationConstructs.html)

-   [Theory: What happens in the intervals between my measurements?]

-   [Theory: What happens during sleep?]

-   [Equally Spaced vs Un-Equally Spaced measurements]
:::

## Number of repeated measurements

The number of measurements is important, as it determines how much detail we get to see. If we only have a few repeated measures, we can only obtain a very rough idea of the underlying processes (e.g., whether it is increasing of decreasing), whereas a larger number of repeated measurements allows for a more detailed perspective on the ongoing process. 

Related to this, the number of repeated measures also determines the amount of information we will have to base our inferences on (i.e., it determines our sample size and hence our certainty about certain conclusions).
If we have enough repeated measurements per person, we may analyze the data of each person separately; the result thus obtained will be useful for making inferences about this specific individual. If we have fewer repeated measurements per person, but we obtained data from multiple persons, we may analyze these together a single model. When the number of repeated measurements is very small (as is the case in panel data, when we have for instance only three measurement occasions), then there is little room for individual differences in our general model; we may only be able to account for stable (mean) differences between individuals. But if we have more repeated measures per person, we may also allow for (quantitative) individual differences in some of the model aspects that are concerned with the underlying dynamics of the process; then we can make inferences about these individual differences as well.  


::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Zoe wants to investigate individual differences in inertia (autoregression) in momentary negative affect, and whether these are related to neuroticism. Hence, she wants to obtain multiple measurmerement of momentary negative affect within a day, for multiple days, and she wants to obtain that data from multiple individuals. She needs to determine how many measures per day, for how many days, and for how many people she will need; there may be some trade-off here (e.g., of she obtains data from more people, she may need fewer repeated measures; if she obtains more measures per day, she needs fewer days), but to what extent such trade-offs work out, is probably very much dependent on the underlying process and the particular model she will use in the statistical analysis.  
:::



::: {.callout-tip collapse="true"}
## Example: Daily diary study

Jayden wants to know for a particular patient how strongly their anxiety is determined by their stress the preceding day. Hence, he wants to do a single-subject (N=1) analysis, and wants to have enough repeated measures to have reasonable power to detect whether a particular cross-lagged parameter is different form zero.   
:::


<!-- Hier expliciet maken hoe dit zich verhoudt tot granularity en meettheoretische aspecten; bv benadrukken dat hoeveel herhaalde metingen je nodig hebt ws ligt aan wat je wil weten om aan te sluiten bij je voorbeelden; meer meten op specifieke momenten/ bursts zouden genoemd kunnen worden,  -->


<!-- Los van de andere twee denk ik niet dat je het aantal metingen kan zien als granularity; dat is de combinatie van interval en de hoeveelheid metingen. Number of measurements gaat meer over hoeveel informatie we hebben, denk ik. Ik heb dit aangepast.-->

<!-- Hier zou een ref naar simulatie werk van Morten en Bengt kunnen.-->


::: {.callout-note collapse="true"}
## Read more: Number of Repeated Measurements

-   [How many repeated measurements do I need?]

-   [Power analysis]

:::

# Time span, coverage and granuality: Combining the three design aspects 

The combination of the three design aspects have major consequences for how much we zoom in or out (i.e., the time span of our study), how much of the ongoing process is captured by our measurements (i.e., coverage of the process), and how much detail we get to see (i.e., the granularuty).



## Time span of a study

The combination of all three aspects determines the time span that is covered by the study. When the intervals are of a fixed length, the exact formula for the study's time span is:

time span  = (number of measurements - 1) * time interval + time frame

<!-- Expliciet maken hoe dit zich verhoudt tot  meettheoretische aspecten; i.e., waarom maakt het uit wat voor time span je hebt; waarom moet je hier over nadenken van te voren. Een belangrijk punt hier is externe validiteit: Je kan bv denken aan het missen van bepaalde events die zeldzaam zijn (related page: event contingency van Pia), missen van seasonality/non-stationarity -->

To understand the reasoning behind this, it is helpful to visualize the repeated measures in time: If we have 4 waves, then we have three intervals between them. Suppose the interval between measurements is one month. Hence, from beginning to end, the study takes three months:

Start: wave 1

After 1 month from the start: wave 2

After 2 months from the start: wave 3

After 3 months from the start: wave 4

If the time frame that is used is referring to the the past week, then the measurements at wave 2 and onward fall within the time interval between the measurements; but the week that is covered by the first measurement actually falls prior to that measurement, which is why we have to add the time frame once. 

In the case of a momentary measurements (``How are you feeling right now?''), the time frame can be considered to be equal to zero here.

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie asks participants at a daily basis about their experiences during the past day. Hence the time frame and the time interval are identical. She obtains these measurements for 28 ways; hence, the time span of her study is 28 days. 
:::


::: {.callout-tip collapse="true"}

## Example: Panel study

Jennifer performed a panel study, consisting of 4 waves with intervals between the measurements of 6 months. The time frame of measurements was the past two weeks. The time span of this study is 18 months and two weeks. 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study 2

Jennifer performed a second panel study, consisting of 5 waves with intervals between the measurements of 2 months. The time frame of measurements was the past two months. The time span of this study is therefore 10 months. 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study 3

Jack performed a panel study consisting of 3 waves, with a measurement interval of 2 years, and a time frame of 1 week. Hence, the total time span of the this study is four years and one week. 
:::


In the case of a momentary measurements ("How are you feeling right now?"), the time frame can be considered to be equal to zero. In that case, the time span of the study is simply the amount of time between the first and last observation. 

<!-- Ik denk dat het in bovenstaand stuk beter werkt om de voorbeelden door de tekst te mengen, zodat elk relateert aan een relevant stukje voorgaande tekst, dan ze allemaal aan het einde te zetten. -->


::: {.callout-note collapse="true"}
## Read more: Time Span

-   [Measurement Burst Designs]

-   [External Validity for ILD]

-   [Event-Related Constructs](../context-events/event-relations.qmd)

:::


## Coverage of the process

When the time frame of the measurement instrument and the time interval between measurements are the same, this implies that the time frames are spaced back to back. In that case, all parts of the ongoing process are captured by exactly one measurement frame. This is for instance the case when we have weekly measures and ask individuals about their experiences during the past week.   



::: {.callout-tip collapse="true"}

## Example: Panel study 

Patrick is conducting a panel study with measurements being one year apart, asking people to rate their well-being over the past year. Hence, the time frame of the measurements is identical to the time interval between the measurements, such that for the entire time span of the study, every moment of the process is captured by exactly one measurement frame. 
:::

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie is performing a daily diary study, in which participants are asked at the end of every day questions such as: "On average, how energetic did you feel today?". At first sight, we may think of this design of consisting of measurement frames that are spaced back to back, because the time frame and the time interval between the measurements are both one day. However, it is somewhat unclear where the participants start the interval for which they will provide an average; if they consider the start of the day when they got up, there may be a considerable part of the ongoing process (between their reporting the preceding day, and their getting op the following day) that is not captured by the measurements.
:::


Alternatively, the time frame may be shorter than the time interval between the measurements. This is the case when using the momentary time frame (i.e., ''right now''), but is also quite common in panel research. In the latter case, the time frame is often determined by the instrument that is used and that has been validated with that particular specification (e.g., the past week or past two weeks). In these cases, there is a proportion of the process that is not covered by any of the measurements. 

::: {.callout-tip collapse="true"}

## Example: Panel study 

Jack performed a panel study consisting of 3 waves, with a measurement interval of 2 years, and a time frame of 1 week. Hence, only 1 week in two years is covered by a measurement frame, meaning that less than 1\% of the ongoing process is captured by the measurements.  
:::


It also happens that the time frame is actually longer than the time interval between measurements; in that case the time frames overlap. A typical case is when participants are asked to rate themselves "in general", or when no specific time interval is provided (e.g., "how true is the following statement of you?").

<!-- voorbeeld van voorgaande -->

::: {.callout-tip collapse="true"}
## Example: Panel study
David performs a panel study in which he measures self-esteem; the measurement waves are six months apart. The participants are asked to indicate how true certain statements are about themselves in general. Hence, individuals may consider themselves from as far back in time as they can remember; they may also consider a somewhat shorter time frame, like the past two years. It is unclear how individuals reach their answer in these cases, but it is very likely that the measurement frames that individuals use overlap.  
:::


<!-- Ik denk dat het in bovenstaand stuk beter werkt om de voorbeelden door de tekst te mengen, zodat elk relateert aan een relevant stukje voorgaande tekst, dan ze allemaal aan het einde te zetten. Gerelateerd aan deze opmerking (dit is niet puur praktisch, lijkt mij):
 The designs discussed all are based on a researcher who decides when measurements are obtained; such a design can be referred to signal contingent. Other designs are event contingent, or interval contingent (see Hektner et al 2007; CHECK DE HAAN ET AL.).-->




## Granularity

The granularity of our study is strongly related to the number of repeated measures, but also to the other two design aspects, that is, the time frame of the measurements and the time interval between the measurements, and their specific combination. Additionally, for a study to have the right kind of granularity, it also needs to suit the timescale at which the phenomenon of interest appears.  

::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is interested in finding out whether positive affect (like: energetic, joyful) peaks in the middle of the day, such that the profile looks like an inverted U-shape. This implies that enough measurements across the day are needed; if only two measurements per day were taken, this pattern could not be detected. Hence, the time interval between the measurements should not be too long, such that within a day, enough measurements are obtained to detect whether this pattern exists.
:::

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie is interested in studying whether people experience more fulfillment on days that they work than on days they do not work. Hence, she performs a daily diary study, in which people report at the end of the day whether or not they worked that day, and how fulfilled they felt that day. In this case, measuring more often (as would be the case in an ESM/EMA design) would not be beneficial. Hence, a time interval of one day between the measurements is sufficient. 
:::

When we have a larger number of measurement occasions, we tend to have more information of the process, simply because the temporal resolution of our image is typically large when there are many measurement occasions. However, this is not necessarily the case (as seen in the example below).

::: {.callout-tip collapse="true"}
## Example: ESM/EMA study
Carl did an ESM study, in which he asked participants 10 times per day for 30 days how much self-esteem they have in general. Individuals may then provide more or less the same answer at all 300 measurement occasions. Thus, while Carl obtains a lot of repeated measurements per person and the time intervals between the measurements are rather short, the measurements do not provide a very detailed image of the process, because the time frames overlap. Had Carl used a different instruction instead (e.g., how much self-esteem did you experience in the past hour, or how much self-esteem do you have right now), the same 300 measurement occasions would provide much more detailed information about the ongoing process. 
:::

When the granularity of a study is low, this implies that it will be difficult to get a good view of the dynamics that govern the underlying process. While it may be possible to determine some crude patterns (e.g., do individuals tend to increase or decrease over time, and are there individual differences therein), if the interest is in how changes in one area precede or follow changes in another, the granularity of our design should fit the timescale of the process we want to study. 

::: {.callout-tip collapse="true"}
## Example: Panel study
Pam obtained three waves of data with three month intervals between the measurement waves. The measures concerned the amount of time that the participants spent on social media in the past week. Given the small number of repeated measures and the low coverage of the ongoing process, the granularity of this study is rather low.  
:::

Hence, if we have a small number of repeated measures, we will have low granularity; however, when the number of repeated measures is large, our study's granularity may be high, but this is not guaranteed, as it depends on the other design aspects and the timescale of the process under investigation as well. 


::: {.callout-note collapse="true"}
## Read more: Aiming your Study's Granularity

-   [Measurement Burst Designs]

-   [Measurement Burst Designs: Event Contingent Bursts]

:::


# Practical Considerations

The following practical considerations are also very important for the decision about the measurement coverage of your study, but are not considered further on this website.

-  The number of repeated measures, intervals, and time frame of your measurement instrument will all affect how much you burden a participant.

- Funding and personnel available will naturally affect how many and how intensively one may collect repeated measures.

- Measurement applications may limit the types of measurement designs you can easily implement.

# Related pages

-   [Designing a measurement instrument to target between-person or within-person variance]
-   [Equally Spaced vs Un-Equally Spaced measurements]
-   [Event-Related Constructs](../context-events/event-relations.qmd)
-   [External Validity for ILD]
-   [How many repeated measurements do I need?]
-   [Relating constructs measured at different timescales](relating-constructs-timescales.qmd)
-   [Measurement Burst Designs]
-   [Measurement Burst Designs: Event Contingent Bursts]
-   [Remembering vs Experiencing Self]
-   [Retrospective Assessment, Ecological Retrospective Assessment, Ecological Momentary Assessment]
-   [Theory: What happens in the intervals between my measurements?]
-   [Theory: What happens during sleep?]



