---
title: Regime switching processes
categories: ['Substantive theory', 'Ergodicity', 'Non-stationarity', 'Regime-switching']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-05-26
date-modified: last-modified
author:
  - name:
      given: Sophie W.
      family: Berkhout
    email: s.w.berkhout@uu.nl
    corresponding: true
    orcid: 0000-0002-4890-2754
    affiliations:
      - name: Methods &amp; Statistics Department, Utrecht University
  - name:
      given: Daan
      family: de Jong
    email: d.dejong@uu.nl
    affiliations:
      - name: Methods &amp; Statistics Department, Utrecht University
csl: ../../resources/styles/apa.csl
citation: true
bibliography: ../../resources/bibliographies/regime-switching-processes.bib
google-scholar: true
---

::: callout-caution

## This page is a draft. This page has not been peer-reviewed yet. 

:::

::: {.callout-note}
## Want to cite this page? See [citation info](regime-switching-processes.html#citation).
:::

This page is about what it means when a proces has sudden transitions or multiple regimes, and how to capture these.

Many processes are not stable over time but may have multiple stable states or regimes. For example, an individual can alter between healthy and depressed states over a period of time, or a couple may switch between conflict, neutral, and happy states.

If a process consist of multiple regimes it switches between, it is important to think about how to capture these different regimes and how to capture when a regime switches in your measurements.

In the following, we discuss how we define a regime and some theoretical considerations for when you want to measure a regime-switching process.

# What is a regime?

There is no clear-cut definition of what a regime is, but every regime has a certain degree of **stability**. Stability has something to do with the notion of a **stable state** in dynamical systems theory, also called stable equilibrium or attractor state [see e.g., @HartelmanEtAl1998]. Perturbations away from the state will have a short-lived effect, because the system will always return back to the stable state.

A process (i.e., system) may have multiple regimes or stable states, which we can observe when we measure this process over time. Each regimes is characterized by certain (statistical) properties, such as a set of parameter values. For example, regimes could have a different mean or inertia.

::: {.callout-tip collapse="true"}

## Example: Two regimes with different means

Gideon wants to see how negative affect evolves over time in a patient diagnosed with bipolar disorder. The patient switches between depressive and manic states while Gideon tracks their negative affect. By looking at the trajectory of negative affect, Gideon can roughly distinguish periods with a high average of negative affect and low average of negative affect.

:::

::: {.callout-tip collapse="true"}

## Example: Two regimes with different inertia

Kate studies how negative affect evolves over time in a patients diagnosed with depression that are currently being treated. She finds overall that when patients are in a state of depression, their momentary negative affect generaly tends to deviate from their average negative affect in the same direction, whereas when patients are in a state of recovery, their momentary negative affect fluctuates more randomly around their average negative affect. When analyzing the autoregressive effect of negative affect per state (i.e., depression and recovery), she finds a smaller autoregressive effect (also known as inertia) in the recovery state compared to the depression state.

:::

# Regime switching

A main topic of research is *how* and *when* regime switches take place. Regime switches can be sudden: from one moment to the next, the process of interest is completely taken over by a different regime (but a regime could also be varying continuously over time, see [Time-varying processes]).

## Regime switching mechanisms

We can distinguish three mechanisms for how regime switches take place, namely a process can excite itself to switch between regimes, an observable control variable causes regime switching in a process, or a latent control variable causes regime switching in a process.

### Self-excited regime switching
A process may switch between regimes due to a change in its own properties. These properties are required to vary over time, otherwise a process would always stay in the same regime. There is a feedback loop that regulates the process when (some of) its properties become too extreme. To capture a self-excited regime switch in a process, you need to observe the relevant changes in properties.

::: {.callout-tip collapse="true"}

## Example: Binge drinking

Marissa studies individuals that suffer from binge drinking. When the participants start a binge drinking episode, they report the amount of alcoholic beverages consumed in the past hour. When participants consumed at least one alcoholic beverage they were more likely to consume more alcoholic beverages in the near future. However, when they reached a certain total amount of alcoholic beverages during the binge drinking epsiode, their alchohol consumption decreased.

:::

### Manifest regime switching
There may be an observable variable that controls the regime switches of a process. This manifest variable needs to vary over time as otherwise it cannot control switches in regimes of a process. To capture a regime switch controlled by a change in a manifest variable, one needs to observe this change.

::: {.callout-tip collapse="true"}

## Example: Workload

Akash works for a big company and investigates the effect of workload experienced by his colleagues on burnout symptoms. He measures perceived workload and severness of several burnout symptoms on a weekly basis and finds that while a higher workload is associated with worse burnout symptoms the following week, overall burnout symptoms bounce back quickly and tend to fluctuate around a healthy average. However, when a colleague persistantly perceives a high workload for at least 6 weeks, the burnout symptoms start fluctuating around a non-healthy average.

:::

### Latent regime switching
Regime switching in a process may also be caused by an unobserved latent construct. To capture a latent regime switching process, one needs to be able to estimate this latent construct in some way. Note that regime switching may also take place based on probabilities and this probabilistic process is also seen as latent.

::: {.callout-tip collapse="true"}

## Example: Depression

Ilja studies how the interplay of several depression symptoms cause individuals to switch between depressive and healthy states. He measures the severness of depression symptoms in participants multiple times per day over several days. On each occasion, he estimates the correlation between the variables and finds overall that when all the correlations are high, an individual is more likely to be in a depressive state at the next moment.

:::

## Timing of regime switches

The regime switching mechanism may only be understood if regime switching takes place during the measurement period. Therefore, it is important to think about the timescale of the regime switching process. For example, if regime switching occurs more frequently than the frequency of the measurements, regime switches may be missed.

::: {.callout-tip collapse="true"}

## Example: Social anxiety

Flora tracks daily social anxiety in a single participant. At the end of each day in the study, the participant reports how socially anxious they felt that day on average. Flora finds that the participant's social anxiety is very stable over time. However, the participant feels very distinct states of anxiety or no anxiety during the day depending on whether or not they are in a social situation which is not captured in the daily average.
:::

::: {.callout-note collapse="true"}
## Read more: Timescales

-   [Key design aspects related to timescales: Time span, process coverage, and granularity](../timescale/time-span-process-coverage-granularity.qmd)

:::

# Practical Considerations

- There may not always be strong theories to determine the amount of regimes in a process. Exploratory analyses may be necessary, where the process needs to be monitored long enough to establish the existance of multiple regimes.
- If you do not know whether there is a control variable that determines when a regime switch takes place and want to measure several different possibilities, bare in mind that longer questionnaires increase the burden on participants and reduce compliance.
- If you want to esimate specific statistical properties within regimes, be aware that some statistical properties may require a larger sample size than others (e.g., a mean needs fewer observations than an autoregression).

# Related pages

- [Stationarity]
- [Time-varying processes]
- [Event-related constructs](../context-events/event-relations.qmd)











