---
title: Event - Relation in ILD Measurement
date-format: "YYYY-MM-DD"
date: 2023-06-19
date-modified: last-modified
author:
  - name: Pia Andresen
    email: p.k.andresen@uu.nl
    corresponding: true
    orcid: 0000-0001-8060-6448
    affiliations:
      - name: Methods &amp; Statistics Department, Utrecht University
  - name: Noémi Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methods &amp; Statistics Department, Utrecht University
citation: true
bibliography: ../../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution

## This page has not been peer-reviewed yet.

:::

::: {.callout-note}
## Want to cite this page? See [citation info](#citation).
:::

In everyday life, people constantly engage with their environment. Consequently, many psychological constructs assessed with ILD should substantively be assumed to be event-related. 

On this page, we will introduce you to several substantive assumptions that you introduce to a study design, by (not) accounting for specific types of event-relations.

# 1. Explicit and implicit assumptions about event-relations 

Many ILD designs do not explicitly account for event-relations in behavior. However, this does not mean that no assumptions are being made about event-relations for the construct of interest. 

Participants will always encounter a number of situations every day, and many of those potentially impact measurement of the construct. If we do not explicitly account for these influences, we are assuming we can ignore those influences when answering our research question. This is often an implicit assumption. If we do want to account for these influences, we typically need to make more explicit assumptions about the mechanism behind these influences.

## Disregarding event-relations: Unconditional Constructs
<!-- I've adjusted the above and below paragraph a bit, so you have new section like this here, that pairs well with the next two. I think then this paragraph should fall under section 2 (the intro for that then needs some adaptation) -->

<!-- intro -->

...treat those influences as random error. This random error is in turn assumed to cancel themselves out - some influences are positive, some negative - over a sufficiently large number of independent observations.

Depending on the specific research context, this may be more or less appropriate. In any case, making this assumption is most reasonable if ones substantive theory states that situational factors are not of a big importance to the process under study. In this case, the process is treated to be <i>unconditional</i>, that is, independent of (unobserved) contextual influences.


::: {.callout-tip collapse="true"}

## Example: Conscientiousness in Daily Life

A researcher is interested in studying the manifestation of trait conscientiousness in daily life. Three times a day, the esm protocol asks participants "How conscientious are you right now?". No situational variables are measured. 

In the resulting time series, the means of the conscientiousness scores of different people correlate highly with trait conscientiousness measured with a cross-sectional personality trait questionnaire. 

The researcher interprets this result in the following way: Trait conscientiousness manifests as the *unconditional mean* of being conscientious in daily life.

:::

In the next section, two ways of accounting for event-relation of constructs will be discussed.

::: {.callout-note collapse="true"}
## Substantive assumptions



## Read more: Topic

- [Time Scales](/)

- [Causality](/)

:::

# 2. What kinds of event-relations can I assume?
<!-- I think that in the below sentence ' an independent occurance' is confusing, because it is kind of not independent. The two are dependent in statistical terms at least for sure. Maybe just leave that bit out.
I removed it now: "is an independent occurrence from the construct, but it"-->

In general, constructs measured in ILD can be related to measurements of events/situations in two ways: 

- The event influences the construct to change in some way (there is some causal relationship between the event and the construct). 

-  The event is a necessary condition for the construct to occur. 

We will discuss both options in more detail next.

<!-- you could explain here why you consider the two mutually exclusive "Note that.."-->

## Contrasts: Constructs affected by Events

In a contrast event-relation, we are interested in the difference in a construct before and after an event occurred. In other words, we are interested in capturing the increase in construct *Y*, that is due to situation/event *S*.
We can express this as:

$$Y{t} = c + b1*S{t-1} + e{t}$$
Here, coefficient *b1* expresses the reaction/contrast created by the event. If no event is reported, *b1* will not influence *Y* at time point *t*.

<!-- Maybe note that this is a very simple example of such a relationship, and that other functional forms are possible too. Or make the simple linear effect an example box too, and use a super general notation in the main text like : y = f(x) , so it is clear that y is a function of x, and it could be any function. -->

::: {.callout-tip collapse="true"}

## Example: Conscientiousness in Daily Life
<!-- if same researcher, use a name and use the same name here -->
The same researcher as before additionally would like to study people's reactions to mess in the workplace as a sign of trait conscientiousness. The hypothesis is that very conscientious people, will strongly react to encountering mess and will report to feel uncomfortable after. For this, they come up with an esm protocol measuring two variables, five times a day. The first variable is *Y = "comfort/discomfort "Right now, to what extend did you feel comfortable/uncomfortable?*, the second variable is *S = "Right now, to what extend are you in a messy environment?"*.

In a model, *S* can be defined to have a lag-1 to lag-d relationship with current measures of *Y*. With this, the researcher is able to estimate the effect of *S* on *Y*. This coefficient can be interpreted to represent a participants tendency to be *reactive to* mess. 

<!-- I think in this example the timing seems off, as in, the lagged approach leaves too much time in between. Maybe this can be changed.-->
:::

### Constrasts: Substantive assumptions

<!-- this needs some intro, like "If you believe there is a contrast relationship like the above, you are making an number of implicit assumptions as well:" -->
- *Y* and *S* are conceptually distinct constructs
- You are interested in the effect of *S* on *Y*
- You are assuming that the variables are measured at the correct time scale
- You are assuming a lagged, causal relationship between *Y* and *S* <!-- I would remove 'lagged' here. It is implied by causal, in my opinion, and people may confuse the theoretical lagged with in practice modeling lagged and get grumpy about this idea. Maybe 'You are assuming that Y is a function of X' is better.-->

::: {.callout-note collapse="true"}
## Read more: Topic

- [Time Scales](../time-scales.qmd)

- [Causal Inference with ILD]

:::


## Conditional Event-Relations of Constructs:

Conditional event-relations differ from contrasts in the substantive assumptions about the relationship between *Y* and *S*. Concretely, here we assume that *Y* only occurs or is only measurable within occurrences of *S*. This is the case if a construct, per definition, cannot be observed in absence of a situational pre-condition. *Y* and *S* may therefore be measured retrospectively and at the same time. As *S* is a necessary condition for *Y*, no lag between the constructs has to be specified. 

::: {.callout-tip collapse="true"}

## Example: Conscientiousness in Daily Life

<!-- use the same name for the researcher, maybe lable your example 1/2/3 to indicate they are related-->
The same researcher as before is furthermore interested in assessing another state measure of daily conscientiousness. Concretely, they think "hardworkingness" is an interesting variable to consider and that high means in state-hardworkingness will correlate with trait Conscientiousness. At first glance, *hardworkingness* appeared to be a normal state variable, which could be measured without accounting for contextual factors. However, at second glance the researcher encounters a problem: When measuring "How hardworking are you right now?", not all measurement occasions are equally important, as there simply is not a lot of *work to do* during weekends or in the evening. Therefore, the researcher includes a situational variable *S* into the procedure, and couples the assessment of *Y* to positive responses on *S*. If "Right now, is there work to be done?" (*S*) is answered with 'yes', *Y* ("How hardworking are you right now?") can be asked.
:::

### Substantive Assumptions
<!-- Needs intro --> 

- You are assuming that *S* and *Y* are conceptually overlapping
- You are assuming that you can only gain a valid measurement of construct *Y* if *S* currently occurs
- You are assuming that *S* does not have a causal effect on *Y* <!-- I'm not sure if this is true. If Y can only exist when S does, would everyone agree this relationship is not causal? -->

<!-- I think some explicit mention needs to be made about how this relates to event-contingent design also in ESM --> 

::: {.callout-note collapse="true"}
## Read more: Topic

- [Event-Contingent Design]

:::




# Practical Considerations

The following practical considerations are also important for the decision studying event-relation with ILD, but are not considered further on this website.

- ESM/EMA protocols for measuring events (link to ESM textbook) <!-- I think this should be in the 'read more' in the previous paragraph rather than as a practical consideration -->

- Consideration 2

# Related pages
<!-- Add related pages, at least the ones already mentioned above -->
- [Related Page Name](/)





