---
title: "Time scale: Measurement coverage, time span, & granularity."
date-format: "YYYY-MM-DD"
date: 2023-06-20
date-modified: last-modified
author:
  - name: Ellen Hamaker
    email: e.l.hamaker@uu.nl
    corresponding: true
    orcid: 
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
  - name: Name Second Author
    email: mail second author
    orcid: 
    affiliations:
      - name: affiliation second author
citation: true
bibliography: ../../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](#citation).
:::

This page is about how specific key design aspects determine how well our repeated measures cover a given process of interest. Two important concepts that determine this coverage are

- the <i> time span </i> of our measurements, which is related to the timing and duration of our measurement procedures/study.

- the <i>granularity</i> of our measurements, which is the temporal resolution with which we observe the process: it can be more or less fine-grained. 

The time span and granularity of a measurement design to a large extent determine at which time scales we can study a given process. In the following, we discuss three important design aspects that determine the time span and granularity of a study.


# Key design aspects that determine measurement coverage

We can distinguish between three key aspects of longitudinal measurement designs that determine granularity (Hamaker, in press), that is: a) the time frame used in the measurement instrument; b) the time interval between measurements; and c) the number of measurements.


## Time frame of the measurement instrument

When using self-report, oftentimes the participant is asked to answer questions with respect to a specific time frame. Similarly, when obtaining measurements that are not based on self-report, the researcher also has to decide with respect to what time frame to obtain the measures.  
<!-- I initially guessed this would be about the duration of the study. I think this needs a better name to indicate it is not the time frame of the study; ie 'time frame of measurement instrument'. -->

::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is performing an ESM/EMA study, in which participants are asked multiple times a day at (semi-)random time points about their momentary experiences. An example of an item is: ''How much tension are you experiencing right now?'' Other items are making reference to an episode prior to the beep, such as: ''Did something stressful happen since the previous beep?'' 
:::

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie is performing a daily diary study, in which participants are asked at the end of every day to whether or to what extent they have had certain experiences that day. Examples of the questions are: ''Did you go to work today?'' and ''On average, how energetic did you feel today?''. Additionally, there are also a few questions about the most extreme experiences that day, such as: ''...?'' 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study

Jennifer performed a panel study, in which she asked participants about their average experiences over a longer period of time. For instance, she asked them: ''How confident did you feel over the past month on average?''. She combines this with measures that are not based on self-report, such as the participants average grade over a semester. 
:::

<!-- Hier expliciet maken hoe dit zich verhoudt tot meettheorie, dwz, waarom is het belangrijk dat men hier over nadenkt bij het opzetten van een design, voorbeelden -->

<!-- Evt andere dingen noemen die iets te maken hebben met time frame en (meet)theorie ; e.g., zijn we geinteresseerd in remembering or experiencing self (read more paginas) Evt IJsbrand inschakelen hiervoor-->

::: {.callout-note collapse="true"}

## Read more: Time frame used in measurement instruments

-   [Retrospective Assessment, Ecological Retrospective Assessment, Ecological Momentary Assessment]

-   [Remembering vs Experiencing Self]

-   [Designing a measurement instrument to target between-person or within-person variance]
:::

## Time interval between measurements

A second key aspect of the longitudinal design is the interval between measurements. These can we long (e.g., a year) or short (e.g., a milisecond), and they may be fixed (i.e., always the same for everyone), or (semi-)random. The latter is often used in self-report studies based on ESM/EMA, as a way to ensure participants are caught while living their daily life, rather than anticipating the next beep. 


::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is performing an ESM/EMA study, in which participants are asked multiple times a day about their momentary experiences. To this end the time between 8am and 9:30pm is divided into blocks of 90 minutes, and within block, at a random time point within that block a beep is given, and the participant is asked to fill out the questionnaire. An additional constrained can be imposed, that beeps need to be at least 15 minutes apart. The resulting data are thus irregularly spaced in time, and characterized by a longer interval for the night break. 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study

Jennifer performed a panel study, with intervals between the measurements of 6 months. 
:::

<!-- Hier expliciet maken waarom dit belangrijk is om over na te denken mbt meet(theory) en substantive theory/beantwoorden onderzoeksvraag. -->
<!-- Evt andere dingen noemen die iets te maken hebben met theorie ; e.g., wat gebeurt er in between metingen/intervals. Evt hier expliciet link maken naar 'wat als verschillende variabelen gemeten zijn met verschillende intervals, verwijzen naar sophie pagina. -->


::: {.callout-note collapse="true"}

## Read more: Time Intervals between Measurements

-   [Constructs Measured at Different Timescales](relating-constructs.qmd)

-   [Theory: What happens in the intervals between my measurements?]

-   [Theory: What happens during sleep?]

-   [Equally Spaced vs Un-Equally Spaced measurements]
:::

## Number of repeated measurements

The number of measurements is important on its own, as it determines the amount of information we will have to base our inferences on (i.e., it determines our sample size and hence our certainty about certain conclusions). Together with the previous two design aspects, it determines the time span of our study, and the amount of detail we get to see of our process; that is, the resolution or granularity of the study.  

<!-- Hier expliciet maken hoe dit zich verhoudt tot granularity en meettheoretische aspecten; bv benadrukken dat hoeveel herhaalde metingen je nodig hebt ws ligt aan wat je wil weten om aan te sluiten bij je voorbeelden; meer meten op specifieke momenten/ bursts zouden genoemd kunnen worden,  -->


<!-- Los van de andere twee denk ik niet dat je het aantal metingen kan zien als granularity; dat is de combinatie van interval en de hoeveelheid metingen. Number of measurements gaat meer over hoeveel informatie we hebben, denk ik. Ik heb dit aangepast.-->

::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is interested in finding out whether positive affect (like: energetic, joyful) peak in the middle of the day, such that the profile looks like an inverted U-shape. This implies that enough measurements across the day are needed; if only two measurements per day were taken, this pattern could not be detected. 
:::

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie is interested in studying whether people experience more fulfillment on days that they work than on days they do not work. Hence, she performs a daily diary study, in which people report at the end of the day whether or not they worked that day, and how fulfilled they felt that day. In this case, measuring more often (as would be the case in an ESM/EMA design) would not be beneficial.  
:::

::: {.callout-note collapse="true"}
## Read more: Number of Repeated Measurements

-   [How many repeated measurements do I need?]
:::

# Time Span & Granularity: Combining the three design aspects 

The combination of the three design aspects have major consequences for how much detail we see and how much of the ongoing process we get to cover with our measurements.

## Granularity: Combination of time frame and time interval

When the time frame of the measurement instrument and the time interval between measurements are the same, this implies that the time frames are spaced back to back. In that case, all parts of the ongoing process are captured by exactly one measurement frame.  

<!-- ik denk dat hier uiteindelijk ook iets moet over remembering vs experiencing self/ ecological retrospective vs ecological momentary assessment (verwijzen naar related page bv). Evt iets over hoe je granularity kan opkrikken rond specifiek interessante events bv (kan een related page zijn over burst designs)--> 

<!-- voorbeeld van voorgaande -->

Alternatively, the time frame may be shorter than the time interval between the measurements. This tends to be the case when using the momentary time frame (i.e., ''right now''), but is also quite common in panel research. In the latter case, the time frame is often determined by the instrument that is used and that has been validated with that particular specification. In these cases, there is a proportion of the process that is not covered by any of the measurements. 

<!-- voorbeeld van voorgaande -->

It also happens that the time frame is actually longer than the time interval between measurements; in that case the time frames overlap. A typical case is when participants are asked to rate themselves ''in general''.

<!-- voorbeeld van voorgaande -->

::: {.callout-tip collapse="true"}
## Example: ESM/EMA study

Pia is using ESM/EMA to study fluctuations in anxiety throughout the day. She is asking participants to indicate how anxious they feel right now, at random time points throughout the day. In this case, most of the ongoing process is not covered by the measurements, although such a momentary snapshot may be representative of the levels of anxiety experience in a considerable period prior and after the specific measurement occasion.  
:::


::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie is performing a daily diary study, in which participants are asked at the end of every day questions such as: ''On average, how energetic did you feel today?''. In this case, it is somewhat unclear where the participants start the interval for which they will provide an average; if they consider the start of the day when they got up, there may be a considerable part of the ongoing process (between their reporting the preceding day, and their getting op the following day) that is not captured by the measurements.
:::

::: {.callout-tip collapse="true"}
## Example: Panel study

Jack is performing a panel study in which participants are asked once every two years how happy they felt during the past week. In this case, only about 1% of the ongoing process is covered by the measurement frames.
:::

<!-- Ik denk dat het in bovenstaand stuk beter werkt om de voorbeelden door de tekst te mengen, zodat elk relateert aan een relevant stukje voorgaande tekst, dan ze allemaal aan het einde te zetten. Gerelateerd aan deze opmerking (dit is niet puur praktisch, lijkt mij):
 The designs discussed all are based on a researcher who decides when measurements are obtained; such a design can be referred to signal contingent. Other designs are event contingent, or interval contingent (see Hektner et al 2007; CHECK DE HAAN ET AL.).-->


::: {.callout-note collapse="true"}
## Read more: Aiming your Study's Granularity

-   [Measurement Burst Designs]

-   [Measurement Burst Designs: Event Contingent Bursts]

:::


## Time Span: Combining time frame of the measurement instrument, time interval, and number of measurements

The combination of all three aspects determines the time span that is covered by the study. When the intervals are of a fixed length, the exact formula for the study time span is:

time span  = (number of measurements - 1) * time interval + time frame

<!-- Expliciet maken hoe dit zich verhoudt tot  meettheoretische aspecten; i.e., waarom maakt het uit wat voor time span je hebt; waarom moet je hier over nadenken van te voren. Een belangrijk punt hier is externe validiteit: Je kan bv denken aan het missen van bepaalde events die zeldzaam zijn (related page: event contingency van Pia), missen van seasonality/non-stationarity -->

::: {.callout-tip collapse="true"}
## Example: Daily diary study

Sophie asks participants at a daily basis about their experiences during the past day. Hence the time frame and the time interval are identical. She obtains these measurements for 28 ways; hence, the time span of her study is 28 days. 
:::


::: {.callout-tip collapse="true"}

## Example: Panel study

Jennifer performed a panel study, consisting of 4 waves with intervals between the measurements of 6 months. The time frame of measurements was the past two weeks. The time span of this study is 18 months and two weeks. 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study 2

Jennifer performed a second panel study, consisting of 5 waves with intervals between the measurements of 2 months. The time frame of measurements was the past two months. The time span of this study is therefore 10 months. 
:::

::: {.callout-tip collapse="true"}

## Example: Panel study 3

Jack performed a panel study consisting of 3 waves, with a measurement interval of 2 years, and a time frame of 1 week. Hence, the total time span of the this study is two years and one week. 
:::

<!-- Ik denk dat het in bovenstaand stuk beter werkt om de voorbeelden door de tekst te mengen, zodat elk relateert aan een relevant stukje voorgaande tekst, dan ze allemaal aan het einde te zetten. -->


::: {.callout-note collapse="true"}
## Read more: Time Span

-   [Measurement Burst Designs]

-   [External Validity for ILD]

-   [Event-Related Constructs](event-relations.qmd)

:::
# Practical Considerations

The following practical considerations are also very important for the decision about the measurement coverage of your study, but are not considered further on this website.

-  The number of repeated measures, intervals, and time frame of your measurement instrument will all affect how much you burden a participant.

- Funding and personnel available will naturally affect how many and how intensively one may collect repeated measures.

- Measurement applications may limit the types of measurement designs you can easily implement.

# Related pages

-   [Designing a measurement instrument to target between-person or within-person variance]
-   [Equally Spaced vs Un-Equally Spaced measurements]
-   [Event-Related Constructs](event-relations.qmd)
-   [External Validity for ILD]
-   [How many repeated measurements do I need?]
-   [Constructs Measured at Different Timescales](relating-constructs.qmd)
-   [Measurement Burst Designs]
-   [Measurement Burst Designs: Event Contingent Bursts]
-   [Remembering vs Experiencing Self]
-   [Retrospective Assessment, Ecological Retrospective Assessment, Ecological Momentary Assessment]
-   [Theory: What happens in the intervals between my measurements?]
-   [Theory: What happens during sleep?]



