---
title: "Instrument landing page"
categories: ['Measurement theory','Instrument', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-07-18
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](instrument.html#citation).
:::

This is the landing page for everything related to the <i> measurement instrument </i> used for measuring your constructs of interest. Note that if you use a single item measure to measure your construct, that item is your instrument (and the [item landing page](item.qmd) may be most helpful).

They way your instrument is designed, from the order of your items to the length of your questionnaire, will directly impact what you measure. 

## Think more about instrument design

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}

## Read more: Instrument design

-   [Using single item or multiple item measures](instrument/single-item-multiple-item-measures.qmd)
-   [Questionnaire design]
-   [Sum or mean scores versus measurement models]


:::

::: {.callout-note collapse="false"}

## Read more: Instrument Validation
-   [Validation landing page](validation.qmd)
-   [When are my measurements good enough?]
-   [Qualitative assessment of your instrument]
-   [Reliability for single items](validation/reliability-single-item-measures.qmd)
-   [Reliability for multiple item measures]
:::
<!--
# Practical Considerations

The following practical considerations are also important for the decision about item design, but are not considered further on this website.

-   Practical consideration 1. -->

```{=html}
<!--
# Related pages

-   [Measurement coverage, time span, & granularity.](/TScale_MeasCoverage.html)

-   [Measuring and Relating Multiple Constructs Measured at Different Timescales](/TScale_RelatingConstructs.html)

-   [Capturing Regime Switches](/TScale_Switches.html)

-   [Event-Relations in ILD Measurement](/EventRelations.html)

-   [Measurement Burst Designs]
-->
```
