---
title: "Measurement model landing page"
categories: ['Measurement theory','Measurement model', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](measurement-model.html#citation).
:::

This is the landing page for everything related to the <i> measurement model </i> that applies to your [constructs](../your-study/constructs.qmd) and [measurement instrument](instrument.qmd).

Your measurement model represents how the true scores of your construct result in the observations you make with your measurement instrument. 

Measurement models are useful for gaining an understanding about your measurement procedure, which is in turn essential for knowing what you can and cannot learn based on your measurements. This understanding is attained by using the measurement model to make explicit what is known about the measurement mechanism, and what is unknown or assumed about the measurement mechanism, preferably in math. 

If the measurement model can be fitted to your data, it can also be a useful tool, for example to filter out measurement error during analyses, or estimating the reliability of your instrument.

## Think more about you sampling design

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}

## Read more: Measurement modeling

-   [Formulating a measurement model]
-   [Classical test theory]
-   [Modern test theory]
-   [Common measurement models: Reflective and formative measurement models]
-   [Means and sum scores versus latent variable models]
-   [Key design aspects related to timescales: Time span, process coverage, and granularity](../../substantive-theory/timescale/time-span-process-coverage-granularity.qmd)]
-   [Using single item or multiple item measures](instrument/single-item-multiple-item-measures.qmd)


:::


```{=html}
<!--
# Related pages

-   [Measurement coverage, time span, & granularity.](/TScale_MeasCoverage.html)

-   [Measuring and Relating Multiple Constructs Measured at Different Timescales](/TScale_RelatingConstructs.html)

-   [Capturing Regime Switches](/TScale_Switches.html)

-   [Event-Relations in ILD Measurement](/EventRelations.html)

-   [Measurement Burst Designs]
-->
```
