---
title: "Sampling landing page"
categories: ['Measurement theory','Sampling', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](sampling.html#citation).
:::

This is the landing page for everything related to the <i> sampling procedure </i> used for measuring your [constructs](../your-study/constructs.qmd) of interest. 

They way your sampling procedure is designed will directly impact what you will be able to capture about your construct. 

## Think more about your sampling design

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}

## Read more: Sampling Design

-   [Types of sampling designs]
-   [Missing observations]
-   [Ecological Momentary Assessment versus Ecological Retrospective Assessment]
-   [Key design aspects related to timescales: time frame, interval, number of measurements](../../substantive-theory/timescale/measurement-coverage-time-span-granularity.qmd)]


:::



```{=html}
<!--
# Related pages

-   [Measurement coverage, time span, & granularity.](/TScale_MeasCoverage.html)

-   [Measuring and Relating Multiple Constructs Measured at Different Timescales](/TScale_RelatingConstructs.html)

-   [Capturing Regime Switches](/TScale_Switches.html)

-   [Event-Relations in ILD Measurement](/EventRelations.html)

-   [Measurement Burst Designs]
-->
```
