---
title: "Validation landing page"
categories: ['Measurement theory', 'Validation', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](validation.html#citation).
:::

This is the landing page for topics related to the <i> validation </i> of measurements.

Validating a measurement means to evaluate whether our measurement instrument is measuring what it is supposed to measure. Validating measurement instruments is a key part of doing any study, ILD studies included: if our measures are invalid, our results may be more or less meaningless. 

There are various approaches to validating a measurement instrument, ranging from doing qualitative studies to see what participants make of the items you designed, to using statistical models to estimate the reliability of an item. Typically, it will require multiple of these approaches together (triangulation) to ensure our measurement instrument is actually valid. 

Read more about various topics related to the validation of ILD studies below.

## Think More About Validation

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Validation - General
-   [When are my measurements good enough?]
-   [Validity for ILD]
-   [Reliability for ILD]
:::

::: {.callout-note collapse="false"}
## Read more: Validation - Validity approaches
-   [Face validity for ILD]
-   [Content validity for ILD]
-   [Predictive, convergent, and divergent validity for ILD]
-   [Qualitative evaluations of measurement instruments]
:::

::: {.callout-note collapse="false"}
## Read more: Validation - Reliability approaches
-   [Reliability for single items](validation\reliability-single-item-measures.qmd)
-   [Reliability for Multiple Item Measures]
:::



<!--  

# Practical Considerations

The following practical considerations are also important for the decision about validation, but are not considered further on this website.

-   Practical consideration 1.-->
