---
title: "Distribution landing Page"
categories: ['Substantive theory','Distributions', 'Landing page']
title-block-categories: false
date-format: "YYYY-MM-DD"
date: 2023-06-26
date-modified: last-modified
author:
  - name:
      given: Noémi K.
      family: Schuurman
    email: n.k.schuurman@uu.nl
    orcid: 0000-0002-6437-5966
    affiliations:
      - name: Methodology &amp; Statistics, Utrecht University
csl: ../resources/styles/apa.csl
citation: true
bibliography: ../resources/bibliographies/pagename_references.bib
google-scholar: true
---

::: callout-caution
## This page has not been peer-reviewed yet.
:::

::: callout-note
## Want to cite this page? See [citation info](distributions.html#citation).
:::

This is the landing page for everything related to the <i> distributions </i> of your [constructs](../your-study/constructs.qmd) of interest.

With distribution we mean how your scores are distributed across the units you are studying. For [intensive longitudinal data](../intensive-longitudinal-data.qmd) we are often interested in how scores are distributed over time within a given unit (e.g., within a person). We may also be interested in how scores are distributed across units (e.g., across multiple persons). 

The distributions of variables imply what scores you should expect for the [process](../processes.qmd) you are studying. Having knowledge about the distribution of your variables of interest is useful for informing your designing your [measurement instrument](../measurement-theory/instrument.qmd) and [sampling design](../measurement-theory/sampling.qmd). It is also important to take into account when you analyse collected data.

## Think More About Distributions

We have collected various topics for you to read more about below.

::: {.callout-note collapse="false"}
## Read more: Distributions general 
-   [Discrete or continuous constructs]
-   [Types of distributions]
-   [Distributional characteristics]
-   [Measurement levels]
-   [Floor and Ceiling Effects](distributions/floor-ceiling-effects.qmd)
:::


```{=html}
<!--
# Related pages

-   [Measurement coverage, time span, & granularity.](/TScale_MeasCoverage.html)

-   [Measuring and Relating Multiple Constructs Measured at Different Timescales](/TScale_RelatingConstructs.html)

-   [Capturing Regime Switches](/TScale_Switches.html)

-   [Event-Relations in ILD Measurement](/EventRelations.html)

-   [Measurement Burst Designs]
-->
```
